version: '3.9'
services:
  app:
    build: .
    volumes:
      - ./bots:/app/bots
    ports:
      - "8000:8000"
    command: uvicorn webarena:app --host 0.0.0.0 --reload
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      # Use localhost so the front-end served to the host browser can reach the backend
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
